version: "3.9"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=server=db;user=root;password=123456;database=casino;port=3306
    depends_on:
      - db

  db:
    image: mysql:8
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: casino
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: